name: Deploy static site to Azure Web App - fixdiorg02

on:
push:
branches:
- main
workflow_dispatch:

jobs:
build:
runs-on: windows-latest

```
steps:
  - uses: actions/checkout@v4

  - name: Upload artifact for deployment
    uses: actions/upload-artifact@v4
    with:
      name: webapp
      path: .
```

deploy:
runs-on: windows-latest
needs: build

```
permissions:
  id-token: write
  contents: read

steps:
  - name: Download artifact from build job
    uses: actions/download-artifact@v4
    with:
      name: webapp

  - name: Login to Azure
    uses: azure/login@v2
    with:
      client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5B75A6F2389843B0BD13422E6A09AE04 }}
      tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6E3FBB898D8D460BA17AF321AD17A521 }}
      subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1633D47D124F40B6914A3D08FB51D517 }}

  - name: Deploy to Azure Web App
    uses: azure/webapps-deploy@v3
    with:
      app-name: 'fixdiorg02'
      slot-name: 'Production'
      package: .
```
